Ds 14 today news home screen
JorgeLVilla/modern-news-app pull request #24
Opened 2021-08-30 23:48 UTC by dannysanchez559

## Changes
_List Changes Introduced by this PR_
1. Add interface implementation for TodayNews endpoint
2. Add TodayNews component
3. Add styled-components file for TodayNews
4. Display Featured news article with bare styling
5. Display Standard news articles with proper grouping and bare styling

Closes #14

2021-08-30 23:52 UTC, kmausolf commented on modern-news-app/src/App.tsx
> +>>>>>>> 26b6d3eb7f70df0ce5e204d189d806c61ef842e1
Looks like a merge artifact.  Do you need help resolving the merge?

2021-08-30 23:53 UTC, kmausolf requested changes
Looks like some merge artifacts are in the code, possibly an incomplete merge.  Let me know if you need help straightening these out.

2021-08-30 23:53 UTC, kmausolf commented on modern-news-app/src/util/fetchApi.ts
> +>>>>>>> 26b6d3eb7f70df0ce5e204d189d806c61ef842e1
Another merge artifact.  Let's clean these up before review.

2021-08-31 16:06 UTC, kmausolf commented on modern-news-app/src/App.tsx
> +      {console.log("newsData ", newsData)}
Log here

2021-08-31 16:09 UTC, kmausolf reviewed
Something about the diff doesn't add up, but the PR seems fine.  Can I have someone do a test run to make sure the app loads correctly?

2021-08-31 16:09 UTC, kmausolf approved these changes

2021-08-31 16:09 UTC, Lap343 commented on modern-news-app/src/App.tsx
> +    // getNewsData("bitcoin");
I would just get rid of this

2021-08-31 16:11 UTC, Gjhnsn approved these changes
Looks good, great job documenting with comments!

2021-08-31 16:11 UTC, Gjhnsn commented on modern-news-app/src/App.tsx
> +      {console.log("newsData ", newsData)}
need this console.log still?

2021-08-31 16:11 UTC, Lap343 commented on modern-news-app/src/App.tsx
>    const getNewsData = async (search: string) => {
same thing with this func since we dont need it anymore

2021-08-31 16:14 UTC, Lap343 approved these changes
The code looks good other than the styled components. It just looks way to bloated. I would recommend for a later refactor. Nest those styles within each other and it will look a lot cleaner.

2021-08-31 16:15 UTC, krferrell approved these changes
Nice work. Everything looking solid.

2021-08-31 16:15 UTC, krferrell commented on modern-news-app/src/App.tsx
>  import { useEffect, useState } from 'react';
I really like this organization of imports

2021-08-31 16:15 UTC, krferrell commented on modern-news-app/src/util/fetchApi.ts
> +}
Might be a good idea to use an interface here for the response to make sure you are getting back what you are looking for.

2021-08-31 16:23 UTC, merged